import type { Metadata } from "next";
import { Nothing_You_Could_Do } from "next/font/google";
import "../styles/globals.css";

const nothingYouCouldDo = Nothing_You_Could_Do({
  weight: '400',
  style: 'normal',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Hercules Machado - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="PT-BR">
      <body className={`${nothingYouCouldDo.className}`}>
        {children}
      </body>
    </html>
  );
}
